Change in config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,23 +20,6 @@ jobs:
           command: echo "NEO4J_AUTH=neo4j/bacco4321" > initial-password.env
 
       - run:
-          name: Update application-test.properties
-          command: |
-            echo "spring.neo4j.uri=bolt://localhost:7687" > src/test/resources/application-test.properties
-            echo "spring.neo4j.authentication.username=neo4j" >> src/test/resources/application-test.properties
-            echo "spring.neo4j.authentication.password=bacco4321" >> src/test/resources/application-test.properties
-            echo "spring.servlet.multipart.max-file-size=20MB" >> src/test/resources/application-test.properties
-            echo "spring.servlet.multipart.max-request-size=20MB" >> src/test/resources/application-test.properties
-      - run:
-          name: Ensure properties file exists
-          command: |
-            if [ ! -f src/test/resources/application-test.properties ]; then
-              echo "Creating src/test/resources/application-test.properties"
-              mkdir -p src/test/resources
-              touch src/test/resources/application-test.properties
-            fi
-
-      - run:
           name: Verify application-test.properties
           command: cat src/test/resources/application-test.properties
 
@@ -47,7 +30,7 @@ jobs:
       - persist_to_workspace:
           root: /home/circleci
           paths:
-            - project
+            - .
 
   build:
     executor: kotlin-executor
@@ -71,6 +54,23 @@ jobs:
             - v1-dependencies-{{ checksum "build.gradle" }}
             - v1-dependencies-
 
+      - run:
+          name: Ensure properties file exists
+          command: |
+            if [ ! -f src/test/resources/application-test.properties ]; then
+              echo "Creating src/test/resources/application-test.properties"
+              mkdir -p src/test/resources
+              touch src/test/resources/application-test.properties
+            fi
+
+      - run:
+          name: Update application-test.properties
+          command: |
+            echo "spring.neo4j.uri=bolt://localhost:7687" > src/test/resources/application-test.properties
+            echo "spring.neo4j.authentication.username=neo4j" >> src/test/resources/application-test.properties
+            echo "spring.neo4j.authentication.password=bacco4321" >> src/test/resources/application-test.properties
+            echo "spring.servlet.multipart.max-file-size=20MB" >> src/test/resources/application-test.properties
+            echo "spring.servlet.multipart.max-request-size=20MB" >> src/test/resources/application-test.properties
 
       - run:
           name: Ensure properties file exists for dev
@@ -107,7 +107,7 @@ jobs:
       - persist_to_workspace:
           root: /home/circleci
           paths:
-            - project
+            - .
 
   test:
     executor: kotlin-executor
@@ -126,14 +126,6 @@ jobs:
           name: Start Neo4j
           command: |
             sudo docker run -d --name test --env-file initial-password.env -p 7477:7474 -p 7687:7687 neo4j:5.12.0
-            sleep 90
-            docker ps -a
-            docker logs test
-            docker inspect test
-
-      - run:
-          name: Inspect Neo4j Logs
-          command: sudo docker logs test
 
       - run:
           name: Wait for Neo4j to be fully up and running
@@ -145,7 +137,7 @@ jobs:
                 break
               fi
               echo "Waiting... $i"
-              sleep 12
+              sleep 10
             done
             docker logs test
 
@@ -154,9 +146,25 @@ jobs:
           command: ls -R build/
 
       - run:
+          name: Verificar conexión con Neo4j usando curl
+          command: |
+            curl -s -u neo4j:bacco4321 http://localhost:7477/browser/
+            if [ $? -ne 0 ]; then
+              echo "Failed to connect to Neo4j"
+              exit 1
+            fi
+            echo "Successfully connected to Neo4j"
+
+      - run:
+          name: Verify Neo4j connection with cypher-shell
+          command: |
+            docker exec test cypher-shell -u neo4j -p bacco4321 -d system "RETURN 42"
+            docker logs test
+
+      - run:
           name: Run tests with detailed logging
           command: |
-            ./gradlew test 
+            ./gradlew test --warning-mode all --info --debug -Dorg.slf4j.simple.SimpleLogger.LEVEL=DEBUG -Dorg.springframework.core.log.LogMessage.LEVEL_TRACE
 
       - store_artifacts:
           path: build/reports/tests/test
